# -*- coding: utf-8 -*-
"""Kode prompt 1 dan 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhWQPCsTHXoo5os59E2LgDgbIxb9G1Px
"""

import pandas as pd #prompt 2
import numpy as np
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression, HuberRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings

# Mengabaikan peringatan iterasi Huber agar output terminal tetap bersih
warnings.filterwarnings('ignore')

# ==========================================
# 1. FUNGSI METRIK KUSTOM
# ==========================================
def mean_absolute_percentage_error(y_true, y_pred):
    """Menghitung MAPE secara manual karena tidak tersedia default di sklearn metrik dasar."""
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# ==========================================
# 2. PIPELINE PREPROCESSING MODULAR
# ==========================================
def build_pipeline(model):
    """
    Membangun pipeline modular.
    Alasan Teknis StandardScaler: 14 fitur arsitektur GPU memiliki skala yang
    berbeda-beda. Regresi linier sensitif terhadap skala fitur; tanpa standardisasi,
    model akan bias terhadap fitur dengan nilai numerik besar.
    """
    return Pipeline([
        ('scaler', StandardScaler()),
        ('regressor', model)
    ])

# ==========================================
# 3. FUNGSI EVALUASI & STRESS TEST (K-FOLD)
# ==========================================
def evaluate_experiment(experiment_name, pipeline, X, y, k_splits=5, inject_stress=False):
    """
    Melatih dan memvalidasi model menggunakan K-Fold Cross Validation.
    Terdapat opsi untuk menyuntikkan outlier buatan (Stress Test) pada data latih.
    """
    print(f"-> Menjalankan Eksperimen: {experiment_name}...")
    kf = KFold(n_splits=k_splits, shuffle=True, random_state=42)

    metrics = {'MAE': [], 'RMSE': [], 'MAPE': [], 'R2': []}

    fold = 1
    for train_index, test_index in kf.split(X):
        # Splitting data
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        # INJEKSI OUTLIER (STRESS TEST)
        # Merusak 5% target pada data latih dengan mengalikannya 10x lipat
        if inject_stress:
            y_train = y_train.copy()
            np.random.seed(42 + fold) # Seed dinamis per fold
            n_outliers = int(0.05 * len(y_train))
            outlier_indices = np.random.choice(len(y_train), n_outliers, replace=False)
            y_train.iloc[outlier_indices] = y_train.iloc[outlier_indices] * 10

        # Fitting model (Otomatis melakukan scaling -> training karena menggunakan Pipeline)
        pipeline.fit(X_train, y_train)

        # Prediksi pada data uji yang BERSIH
        y_pred = pipeline.predict(X_test)

        # Kalkulasi Metrik
        metrics['MAE'].append(mean_absolute_error(y_test, y_pred))
        metrics['RMSE'].append(np.sqrt(mean_squared_error(y_test, y_pred)))
        metrics['MAPE'].append(mean_absolute_percentage_error(y_test, y_pred))
        metrics['R2'].append(r2_score(y_test, y_pred))
        fold += 1

    # Mengembalikan rata-rata metrik dari 5 fold
    return {
        'Model/Kondisi': experiment_name,
        'MAE (ms)': np.round(np.mean(metrics['MAE']), 4),
        'RMSE (ms)': np.round(np.mean(metrics['RMSE']), 4),
        'MAPE (%)': np.round(np.mean(metrics['MAPE']), 4),
        'R2 Score': np.round(np.mean(metrics['R2']), 4)
    }

# ==========================================
# 4. EKSEKUSI UTAMA (MAIN)
# ==========================================
if __name__ == "__main__":
    # A. Load Data
    print("Membaca dataset SGEMM GPU (241.600 baris)...")
    df = pd.read_csv('sgemm_product.csv')

    # 14 kolom pertama adalah fitur, 4 kolom terakhir adalah target (Run1-Run4)
    X = df.iloc[:, :14]
    y_raw = df.iloc[:, 14:]

    # B. Preprocessing Target (Averaging 4 Run Time menjadi 1 target kontinu)
    y = y_raw.mean(axis=1)

    log_experiment = []

    # C. EKSPERIMEN KONDISI NORMAL (Tanpa Outlier)
    pipeline_ols = build_pipeline(LinearRegression())
    log_experiment.append(evaluate_experiment("Baseline OLS (Normal)", pipeline_ols, X, y))

    pipeline_huber = build_pipeline(HuberRegressor(epsilon=1.35, max_iter=500))
    log_experiment.append(evaluate_experiment("Huber Regressor (Normal)", pipeline_huber, X, y))

    # D. EKSPERIMEN STRESS TEST (Injeksi 5% Outlier)
    log_experiment.append(evaluate_experiment("Baseline OLS (Stress Test)", pipeline_ols, X, y, inject_stress=True))
    log_experiment.append(evaluate_experiment("Huber Regressor (Stress Test)", pipeline_huber, X, y, inject_stress=True))

    # E. CETAK LOG EXPERIMENT
    print("\n" + "="*85)
    print("TABEL LOG EXPERIMENT (Siap disalin ke Laporan)")
    print("="*85)
    df_log = pd.DataFrame(log_experiment)
    print(df_log.to_string(index=False))

import pandas as pd #prompt 1
import numpy as np
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression, HuberRegressor, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings

warnings.filterwarnings('ignore')

# ==========================================
# 1. FUNGSI METRIK KUSTOM
# ==========================================
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# ==========================================
# 2. PIPELINE PREPROCESSING MODULAR
# ==========================================
def build_pipeline(model):
    return Pipeline([
        ('scaler', StandardScaler()),
        ('regressor', model)
    ])

# ==========================================
# 3. FUNGSI EVALUASI & STRESS TEST (K-FOLD)
# ==========================================
def evaluate_experiment(experiment_name, pipeline, X, y, k_splits=5, inject_stress=False):
    print(f"-> Menjalankan Eksperimen: {experiment_name}...")
    kf = KFold(n_splits=k_splits, shuffle=True, random_state=42)

    metrics = {'MAE': [], 'RMSE': [], 'MAPE': [], 'R2': []}

    fold = 1
    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        # INJEKSI OUTLIER (STRESS TEST)
        if inject_stress:
            y_train = y_train.copy()
            np.random.seed(42 + fold)
            n_outliers = int(0.05 * len(y_train))
            outlier_indices = np.random.choice(len(y_train), n_outliers, replace=False)
            y_train.iloc[outlier_indices] = y_train.iloc[outlier_indices] * 10

        pipeline.fit(X_train, y_train)
        y_pred = pipeline.predict(X_test)

        metrics['MAE'].append(mean_absolute_error(y_test, y_pred))
        metrics['RMSE'].append(np.sqrt(mean_squared_error(y_test, y_pred)))
        metrics['MAPE'].append(mean_absolute_percentage_error(y_test, y_pred))
        metrics['R2'].append(r2_score(y_test, y_pred))
        fold += 1

    return {
        'Model / Kondisi': experiment_name,
        'MAE (ms)': np.round(np.mean(metrics['MAE']), 4),
        'RMSE (ms)': np.round(np.mean(metrics['RMSE']), 4),
        'MAPE (%)': np.round(np.mean(metrics['MAPE']), 4),
        'R2 Score': np.round(np.mean(metrics['R2']), 4)
    }

# ==========================================
# 4. EKSEKUSI UTAMA (MAIN)
# ==========================================
if __name__ == "__main__":
    print("Membaca dataset SGEMM GPU (241.600 baris)...")
    df = pd.read_csv('sgemm_product.csv')

    X = df.iloc[:, :14]
    y_raw = df.iloc[:, 14:]
    y = y_raw.mean(axis=1)

    log_experiment = []

    # Mendefinisikan 5 Model Regresi Linier
    models = {
        "1. OLS (Baseline)": LinearRegression(),
        "2. Ridge (L2)": Ridge(),
        "3. Lasso (L1)": Lasso(alpha=0.1),
        "4. ElasticNet": ElasticNet(alpha=0.1),
        "5. Huber (Robust)": HuberRegressor(epsilon=1.35, max_iter=500)
    }

    print("\n--- FASE 1: KONDISI NORMAL (TANPA OUTLIER) ---")
    for name, model in models.items():
        pipeline = build_pipeline(model)
        log_experiment.append(evaluate_experiment(f"{name} - Normal", pipeline, X, y))

    print("\n--- FASE 2: KONDISI STRESS TEST (INJEKSI 5% OUTLIER) ---")
    for name, model in models.items():
        pipeline = build_pipeline(model)
        log_experiment.append(evaluate_experiment(f"{name} - Stress Test", pipeline, X, y, inject_stress=True))

    # CETAK LOG EXPERIMENT
    print("\n" + "="*95)
    print("TABEL LOG EXPERIMENT (10 EKSPERIMEN)")
    print("="*95)
    df_log = pd.DataFrame(log_experiment)
    print(df_log.to_string(index=False))