# -*- coding: utf-8 -*-
"""Kode Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aw9md68f3a_DcdGYjuKfZ_Q2A9xXSIWA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression, HuberRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings

# Mengabaikan peringatan iterasi Huber agar output terminal tetap bersih
warnings.filterwarnings('ignore')

CONFIG = {
   'DATA_PATH': 'sgemm_product.csv',
    'OUTLIER_PERCENTAGE': 0.05,
    'MULTIPLIER': 10,
    'LOG_FILENAME': 'log_experiment_final.csv',
    'PLOT_FILENAME': 'perbandingan_model.png' }

# ==========================================
# 1. FUNGSI METRIK KUSTOM
# ==========================================
def mean_absolute_percentage_error(y_true, y_pred):
    """Menghitung MAPE secara manual karena tidak tersedia default di sklearn metrik dasar."""
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# ==========================================
# 2. PIPELINE PREPROCESSING MODULAR
# ==========================================
def build_pipeline(model):
    """
    Membangun pipeline modular.
    Alasan Teknis StandardScaler: 14 fitur arsitektur GPU memiliki skala yang
    berbeda-beda. Regresi linier sensitif terhadap skala fitur; tanpa standardisasi,
    model akan bias terhadap fitur dengan nilai numerik besar.
    """
    return Pipeline([
        ('scaler', StandardScaler()),
        ('regressor', model)
    ])

# ==========================================
# 3. FUNGSI EVALUASI & STRESS TEST (K-FOLD)
# ==========================================
def evaluate_experiment(experiment_name, pipeline, X, y, k_splits=5, inject_stress=False):
    """
    Melatih dan memvalidasi model menggunakan K-Fold Cross Validation.
    Terdapat opsi untuk menyuntikkan outlier buatan (Stress Test) pada data latih.
    """
    print(f"-> Menjalankan Eksperimen: {experiment_name}...")
    kf = KFold(n_splits=k_splits, shuffle=True, random_state=42)

    metrics = {'MAE': [], 'RMSE': [], 'MAPE': [], 'R2': []}

    fold = 1
    for train_index, test_index in kf.split(X):
        # Splitting data
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        # INJEKSI OUTLIER (STRESS TEST)
        # Merusak 5% target pada data latih dengan mengalikannya 10x lipat
        if inject_stress:
            y_train = y_train.copy()
            np.random.seed(42 + fold) # Seed dinamis per fold
            n_outliers = int(0.05 * len(y_train))
            outlier_indices = np.random.choice(len(y_train), n_outliers, replace=False)
            y_train.iloc[outlier_indices] = y_train.iloc[outlier_indices] * 10

        # Fitting model (Otomatis melakukan scaling -> training karena menggunakan Pipeline)
        pipeline.fit(X_train, y_train)

        # Prediksi pada data uji yang BERSIH
        y_pred = pipeline.predict(X_test)

        # Kalkulasi Metrik
        metrics['MAE'].append(mean_absolute_error(y_test, y_pred))
        metrics['RMSE'].append(np.sqrt(mean_squared_error(y_test, y_pred)))
        metrics['MAPE'].append(mean_absolute_percentage_error(y_test, y_pred))
        metrics['R2'].append(r2_score(y_test, y_pred))
        fold += 1

    # Mengembalikan rata-rata metrik dari 5 fold
    return {
        'Model': experiment_name.split(" (")[0],
        'Kondisi': "Stress Test" if inject_stress else "Normal",
        'MAE (ms)': np.round(np.mean(metrics['MAE']), 4),
        'RMSE (ms)': np.round(np.mean(metrics['RMSE']), 4),
        'MAPE (%)': np.round(np.mean(metrics['MAPE']), 4),
        'R2 Score': np.round(np.mean(metrics['R2']), 4)
    }

# ==========================================
# 4. EKSEKUSI UTAMA (MAIN)
# ==========================================
if __name__ == "__main__":
    # A. Load Data
    print(f"Membaca datasets dari {CONFIG['DATA_PATH']}...")
    df = pd.read_csv(CONFIG['DATA_PATH'], dtype=np.float32)

    # 14 kolom pertama adalah fitur, 4 kolom terakhir adalah target (Run1-Run4)
    X = df.iloc[:, :14]
    # B. Preprocessing Target (Averaging 4 Run Time menjadi 1 target kontinu)
    y = df.iloc[:, 14:].mean(axis=1) # Corrected: Assign directly to 'y'

    log_experiment = []

    # C. EKSPERIMEN KONDISI NORMAL (Tanpa Outlier)
    pipeline_ols = build_pipeline(LinearRegression())
    log_experiment.append(evaluate_experiment("Baseline OLS (Normal)", pipeline_ols, X, y))

    pipeline_huber = build_pipeline(HuberRegressor(epsilon=1.35, max_iter=500))
    log_experiment.append(evaluate_experiment("Huber Regressor (Normal)", pipeline_huber, X, y))

    # D. EKSPERIMEN STRESS TEST (Injeksi 5% Outlier)
    log_experiment.append(evaluate_experiment("Baseline OLS (Stress Test)", pipeline_ols, X, y, inject_stress=True))
    log_experiment.append(evaluate_experiment("Huber Regressor (Stress Test)", pipeline_huber, X, y, inject_stress=True))

    # E. CETAK LOG EXPERIMENT
    print("\n" + "="*85)
    print("TABEL LOG EXPERIMENT (Siap disalin ke Laporan)")
    print("="*85)
    df_log = pd.DataFrame(log_experiment)
    print(df_log.to_string(index=False))

    #tambahan ekspor ke csv
    df_log.to_csv(CONFIG['LOG_FILENAME'], index=False)
    print(f"\n[INFO] Tabel berhasil disimpan ke: {CONFIG['LOG_FILENAME']}")

    #tambahan grafik
    print("grafik perbandingan")
    plt.figure(figsize=(10, 6))
    sns.barplot(data=df_log, x='Model', y='MAPE (%)', hue='Kondisi')
    plt.title('Perbandingan MAPE: Normal vs Stress Test', fontsize=14)
    plt.ylabel('MAPE (%) - Semakin Kecil Semakin Baik')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.savefig(CONFIG['PLOT_FILENAME'])
    plt.show()
    print(f"[INFO] Grafik berhasil disimpan ke: {CONFIG['PLOT_FILENAME']}")